-- 찜한 도서 목록 임의의 데이터 삽입
      
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (4, 350481135); -- 회원 4번이 책 350481135번을 찜함
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (4, 317934373); -- 회원 4번이 책 317934373번을 찜함
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (4, 346461236); -- 회원 4번이 책 346461236번을 찜함

SELECT * FROM "TB_FAVORITE";

SELECT b.BOOK_ID, b.TITLE, b.AUTHOR, b.COVER_URL, b.CUSTOMER_REVIEW_RANK
FROM TB_FAVORITE f
JOIN TB_BOOKS b ON f.BOOK_ID = b.BOOK_ID
WHERE f.MEMBER_NO = 4; -- 회원 번호 4번의 찜한 도서 목록 조회


INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (6, 343124315); -- 회원 6번이 책 343124315번을 찜함
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (6, 329386807); -- 회원 6번이 책 329386807번을 찜함
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (6, 176021392); -- 회원 6번이 책 176021392번을 찜함
INSERT INTO TB_FAVORITE (MEMBER_NO, BOOK_ID) VALUES (6, 352205705); -- 회원 6번이 책 352205705번을 찜함

SELECT b.BOOK_ID, b.TITLE, b.AUTHOR, b.COVER_URL, b.CUSTOMER_REVIEW_RANK
FROM TB_FAVORITE f
JOIN TB_BOOKS b ON f.BOOK_ID = b.BOOK_ID
WHERE f.MEMBER_NO = 6; -- 회원 번호 6번의 찜한 도서 목록 조회


SELECT * FROM "TB_MEMBER";

SELECT
	MEMBER_NO,
	MEMBER_ID,
	MEMBER_NICKNAME,
	MEMBER_PW,
	MEMBER_TEL,
	MEMBER_ADDRESS,
	PROFILE_IMG,
	MEMBER_AUTH,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24"시" MI"분" SS"초"') ENROLL_DATE,
	MEMBER_BOOK_CATEGORY
FROM
	"TB_MEMBER"
WHERE
	MEMBER_ID = 'user02'
	AND MEMBER_DEL_FL = 'N';
	

-- 비밀번호 조회
SELECT MEMBER_PW
FROM "TB_MEMBER"
WHERE MEMBER_NO = '6';
	
	
SELECT * FROM TB_BOARD WHERE MEMBER_NO = 6;	
	

-- 6번 회원의 임시 게시글 데이터 생성
BEGIN
   FOR I IN 1..10 LOOP
      
      INSERT INTO "TB_BOARD"
      VALUES(SEQ_BOARD_NO.NEXTVAL,
                SEQ_BOARD_NO.CURRVAL || '번째 게시글',
                SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다',
                DEFAULT, -- 작성일
                SYSDATE, -- 업뎃
                DEFAULT, -- 조회수
                DEFAULT, -- 삭제여부
                6, -- 회원번호
                CEIL( DBMS_RANDOM.VALUE(1,3) ), --보드코드
                NULL,
                DEFAULT,-- 추천수
                DEFAULT -- 비밀글 여부 체크
      );
      
   END LOOP;
END;
	
	
-- 6번 회원의 게시글 목록 불러오기
SELECT 
    b.BOARD_NO, 
    b.BOARD_TITLE,
    b.BOARD_CONTENT,
	b.BOARD_WRITE_DATE,
	b.READ_COUNT,
	b.BOARD_CODE,
    m.MEMBER_NICKNAME AS MEMBER_NICKNAME
FROM "TB_BOARD" b
JOIN "TB_MEMBER" m ON b.MEMBER_NO = m.MEMBER_NO
WHERE b.MEMBER_NO = 6;
	
	
COMMIT;	


SELECT SEQ_COMMENT_NO.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

-- 댓글 

/* 댓글 ("COMMNET") 테이블에 샘플 데이터 추가*/

BEGIN
	FOR I IN 2..300 LOOP
	
		INSERT INTO "TB_COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT,  -- COMMENT_DEL_FL 기본값 ('N')
            DEFAULT,  -- COMMENT_REGL_DATE 기본값 (SYSDATE)
            NULL,     -- PARENT_COMMENT_NO는 NULL로 설정하여 부모 댓글이 없음을 표시
            6,        -- MEMBER_NO: 6번 회원
            I         -- BOARD_NO: 2번부터 300번까지 게시글 번호로 설정
		);
	END LOOP;
END;

COMMIT;


-- 게시글 번호 최소값, 최대값
SELECT MIN(BOARD_NO), MAX(BOARD_NO) FROM "BOARD";

-- 댓글 삽입 확인
SELECT BOARD_NO, COUNT(*) 
FROM "TB_COMMENT"
GROUP BY BOARD_NO
ORDER BY BOARD_NO;


-- 6번 회원의 댓글 목록 불러오기
SELECT 
    c.COMMENT_NO , 
    c.COMMENT_TEXT, 
    m.MEMBER_NICKNAME AS MEMBER_NICKNAME
FROM "TB_COMMENT" c
JOIN "TB_MEMBER" m ON c.MEMBER_NO = m.MEMBER_NO
WHERE c.MEMBER_NO = 6;

--
SELECT c.COMMENT_NO,
       c.COMMENT_TEXT,
       c.COMMENT_DEL_FL,
       c.COMMENT_REGI_DATE,
       c.PARENT_COMMENT_NO,
       m.MEMBER_NICKNAME AS MEMBER_NICKNAME
FROM TB_COMMENT c
JOIN TB_MEMBER m ON c.MEMBER_NO = m.MEMBER_NO
WHERE c.MEMBER_NO = 6
ORDER BY c.COMMENT_NO DESC;


-- 게시글 상세 조회


SELECT * FROM "TB_BOARD";



	